### ISSUE TITLE
Are Instructions up to date?

### ISSUE THREAD

**Issue by layeddie** [dwyl/phoenix-liveview-chat-example#114]
Having some problems following the instructions
elixir -v
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

 mix phx.new -v                                      
Phoenix installer v1.7.0

First error - section 2
Create the lib/liveview_chat_web/views/message_view.ex file: creates this error but file contents pasted from instructions.

mix phx.server
Compiling 1 file (.ex)

== Compilation error in file lib/liveview_chat_web/views/message_view.ex ==
** (UndefinedFunctionError) function LiveviewChatWeb.view/0 is undefined or private
    LiveviewChatWeb.view()
    expanding macro: LiveviewChatWeb.__using__/1
    lib/liveview_chat_web/views/message_view.ex:2: LiveviewChatWeb.MessageView (module)
    (elixir 1.14.3) expanding macro: Kernel.use/2
    lib/liveview_chat_web/views/message_view.ex:2: LiveviewChatWeb.MessageView (module)

Delete files paragraph is asking to delete default generated code folders and files that do not exist.
_Finally you can delete all the default generated code linked to the PageController:_

    rm test/liveview_chat_web/controllers/page_controller_test.exs
    rm lib/liveview_chat_web/controllers/page_controller.ex
    rm test/liveview_chat_web/views/page_view_test.exs
    rm lib/liveview_chat_web/views/page_view.ex
    rm -r lib/liveview_chat_web/templates/page

**Comment by layeddie** [comment]
> Hi @layeddie indeed. this one of the tutorials that we haven't updated _yet_. ⏳
> 
> https://github.com/dwyl/phoenix-liveview-chat-example/blob/5605108bd7c96a984c59923f8337eb21ba4d66a2/mix.exs#L45
> 
> If you need a `Phoenix 1.7` Tutorial, consider: https://github.com/dwyl/phoenix-chat-example

Thankyou - it wasnt me going mad then.

**Comment by nelsonic** [comment]
# Todo

+ [ ] Go through the tutorial and update to _latest_ `Phoenix` + `LiveView` and 
+ [ ] Update the `README.md` accordingly
+ [ ] Ensure that the deployment to `Fly.io` is working
+ [ ] Wipe the DB so that we can clear the _noise_:

<img width="997" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/04d39526-a540-4635-a360-40e72c03a675">

+ [ ] Seed some real-looking chat into the `Fly.io` app to set the tone.

**Comment by nelsonic** [comment]
@SimonLab given that you've done the most work on this repo I wanted to give you the chance to make the updates. 👌

**Comment by chargio** [comment]
I have started working on an updated version of the tutorial. Would that be ok?
- [ ] Using context instead of a plain schema for the messages, keeping the boundary in its context.
- [ ] Updating to use Tailwind with a two columns set (one for messages, one for presence)
- [ ] Delete views as they are no longer used
- [ ] Create components for messages


The changes are significant, so review will be hard. Let me know if you are ok with that. I will create a version in its own repo so you can decide if it is worth it.
