### ISSUE TITLE
Chore: `auth` (`/login`) Internal Server Error 💔 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-chat-example#147]
At present this app is _semi_-working on `Fly`: https://liveview-chat-example.fly.dev

<img width="997" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/6d63b396-ddcc-427e-b3cc-00b8006fb47b">

Sadly, `auth` is _not_ working: https://liveview-chat-example.fly.dev/login
<img width="943" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/81b254e0-c17b-4948-89eb-af1bbefcb43d">

A quick look at the logs:  https://fly.io/apps/liveview-chat-example/monitoring
<img width="1248" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/ee32d45d-a44f-4186-b093-a0cdf87a3795">

we see that the error is: 

```sh
2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] Request: GET /login

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] ** (exit) an exception was raised:

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] ** (FunctionClauseError) no function clause matching in Regex.run/3

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (elixir 1.14.1) lib/regex.ex:335: Regex.run(~r/^(.*)\/(.*)\/(.*)$/, nil, [])

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (auth_plug 1.5.2) lib/token.ex:60: AuthPlug.Token.auth_url/0

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (auth_plug 1.5.2) lib/auth_plug.ex:194: AuthPlug.get_auth_url/2

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (liveview_chat 1.7.0) lib/liveview_chat_web/controllers/auth_controller.ex:25: LiveviewChatWeb.AuthController.login/2

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (liveview_chat 1.7.0) lib/liveview_chat_web/controllers/auth_controller.ex:1: LiveviewChatWeb.AuthController.action/2

2023-07-22T07:29:31.789 app[6e82d924a59048] lhr [info] (liveview_chat 1.7.0) lib/liveview_chat_web/controllers/auth_controller.ex:1: LiveviewChatWeb.AuthController.phoenix_controller_pipeline/2
```

`auth_plug@1.5.2` is the _latest_ version: https://github.com/dwyl/auth_plug/tags
So my guess is that the **`AUTH_API_KEY` Environment Variable** is not available ... 🤷‍♂️ 

Yep! That's it:  https://fly.io/apps/liveview-chat-example/secrets no **`AUTH_API_KEY`** ... 🙃 
<img width="1139" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/381eab41-d5ef-4183-b69f-e73b3376e63b">

So this should be a reasonably quick fix! 

# Todo

+ [x] Follow the instructions in: https://github.com/dwyl/auth_plug#2-get-your-auth_api_key- 👀 
+ [x] Add the key to `Fly.io`: https://fly.io/docs/rails/the-basics/configuration/ 🔑 
e.g: `fly secrets set AUTH_API_KEY=keyhere -a=liveview-chat-example`
+ [x] Relaunch the `App` if it doesn't do it automatically ♻️ 
+ [x] Test that `/login` is working.

**Comment by nelsonic** [comment]
`AUTH_API_KEY` https://authdemo.fly.dev/apps/47 added: 
<img width="853" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/1655bcda-4154-439d-a05b-236c2b4e5b41">

Redirect works:
<img width="1275" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/02739dcb-1c08-41e8-b84e-4783dd16a9e2">

Auth working: 
<img width="941" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/dbb94afd-eb93-48af-b36a-a40b48517467">

<img width="941" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/621e6330-5770-45fc-99f7-6a5a929c9bb3">

 
Took me longer to `describe` the issue than it to _fix_ it: 🧑‍💻 ⏳ 
<img width="908" alt="image" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/bb0d7452-9a98-4e56-acb8-831ad16d054d">

<img width="500" alt="this is the way" align="centre" src="https://github.com/dwyl/phoenix-liveview-chat-example/assets/194400/da3046b7-0cd3-440c-8b69-83c94473ee79">
