### ISSUE TITLE
Chore: Migrate Demo App from `Heroku` to `Fly.io`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-chat-example#86]
Sadly, all "free" Heroku Apps will be deleted this month ...  ref: https://github.com/dwyl/learn-heroku/issues/52 🤦‍♂️ 

# Todo

+ [ ] Migrate app to `liveview-chat.fly.dev` 
+ [ ] Update deployment docs in `README.md`
+ [ ] `DELETE` any files related to `Heroku` deployment
+ [ ] Add GIF of working App 
+ [ ] Update URL in repo settings 
+ [ ] ***`DELETE`*** Heroku App! ✂️

**Comment by LuchoTurtle** [comment]
I've been trying to have a go at this for quite some time.

At first, I was having trouble connecting to the Postgres SQL database due to not having the `:ssl` configuration present.

```sh
** (RuntimeError) SSL connection can not be established because `:ssl` application is not started,
         you can add it to `extra_applications` in your `mix.exs`:
```

But now I keep getting an error at the end of the deployment phase...

```sh
 1 desired, 1 placed, 0 healthy, 1 unhealthy
--> v1 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v2 
```

Will investigate further, I guess
